<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">

  <title>
    Blog Post
  </title>

  <link rel="stylesheet" href="../css/reset.css">
  <link rel="stylesheet" href="../css/main.css">
  <link rel="stylesheet" href="../css/side-nav.css">
  <link rel="stylesheet" href="../css/specific-post.css">
</head>

<body>
  <header>
    <?php include "../html/side-nav.html" ?>
  </header>
  <main>
    <div class = "post">
      <h1>Title</h1>
      <p class = "blog"> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur non ultricies elit. Donec ullamcorper eleifend ante at efficitur. Morbi vitae felis metus. Phasellus a ligula orci. Proin at nulla vitae neque elementum dapibus. Suspendisse in dapibus quam. In fermentum, ante sit amet placerat tincidunt, erat lectus luctus felis, sed consequat sem ligula sed orci. Nunc hendrerit lacus ante, ut vulputate felis pharetra et.
        Vivamus auctor augue ac egestas tincidunt. Morbi augue metus, varius et lacus nec, mollis venenatis orci. Mauris vitae magna tincidunt elit viverra accumsan. Quisque varius, enim nec interdum condimentum, lorem erat lobortis orci, varius mollis dolor ipsum quis lectus. In a eleifend nunc, eu pretium diam. Aliquam blandit ultricies sapien, in porttitor ante laoreet sit amet. Fusce at hendrerit turpis, gravida convallis odio. Curabitur vel blandit quam, quis pharetra ipsum. Maecenas at ex ac ipsum placerat tincidunt vel nec elit. Duis vel fringilla elit. Duis vel ullamcorper lorem, ut imperdiet mi.
        Vivamus rutrum tincidunt nulla in fermentum. Praesent ipsum sapien, tincidunt a nisi eget, posuere vulputate justo. Donec ac mollis enim. Mauris mattis efficitur diam, sit amet aliquet lectus. Proin sed nunc a nulla condimentum pulvinar nec nec mauris. Etiam eget lectus eget enim scelerisque tempor in sit amet risus. Aliquam vulputate libero eu nisi eleifend dignissim. Phasellus ullamcorper erat ut turpis pharetra, ac ullamcorper ex euismod. Proin maximus congue neque, quis aliquet diam auctor ut. Proin auctor ligula porttitor, egestas metus quis, pellentesque turpis. Vivamus nec volutpat orci, vel suscipit enim. Curabitur fringilla ligula non lorem lobortis, non laoreet ex ultricies.
        Etiam nibh orci, pretium eget pretium aliquam, ultricies lobortis orci. Pellentesque nec lacus nunc. Sed molestie elit eget nulla tincidunt, sed vestibulum velit elementum. Mauris et orci lacus. Praesent a interdum ex, vitae tristique massa. Quisque erat ex, sollicitudin eget ultrices non, maximus sit amet nisl. Nulla ipsum justo, pharetra blandit nunc eget, auctor finibus ante. Nunc dignissim velit a libero laoreet viverra.
        Fusce at nulla urna. In hac habitasse platea dictumst. Aliquam molestie leo ac consequat sodales. Maecenas auctor, mi ac tempus semper, dolor sapien efficitur risus, vel pellentesque dui mi non justo. Nullam sed interdum eros. Nulla sit amet nisi volutpat, suscipit sem sed, vestibulum ligula. Integer vel magna nunc. Suspendisse potenti. Maecenas luctus placerat neque, a elementum neque feugiat vel. Nam egestas euismod ligula nec facilisis. Morbi vel dapibus orci. Duis congue suscipit sodales. Aenean consectetur dictum convallis. Nunc risus purus, consequat sed lectus ac, bibendum hendrerit lorem.
        Nunc suscipit sollicitudin mi, id tristique odio. Nam ornare, massa vel porttitor dignissim, mi elit tristique nisi, et consectetur nunc tellus ut leo. Cras viverra dapibus dui, in imperdiet sapien rutrum nec. Phasellus sem risus, maximus et ipsum id, ultricies imperdiet ligula. Mauris fermentum erat eget leo ullamcorper pharetra. Proin rutrum eleifend sapien. Phasellus luctus risus nibh, nec hendrerit lectus elementum vel. Nam sed metus elementum, iaculis lorem eu, condimentum purus. Nam ultrices iaculis magna sit amet molestie. Ut tempor odio sit amet dolor lacinia, eu aliquet felis aliquet. Maecenas vel ipsum scelerisque, dictum sapien ac, tempor lorem. Pellentesque ac magna at velit fermentum semper. Aenean ullamcorper cursus leo. Sed convallis, nunc ut lobortis maximus, ipsum nisl ornare eros, tincidunt scelerisque purus mi nec purus. In hac habitasse platea dictumst. Ut elementum ultrices diam.
        Nam feugiat, ante in pellentesque sollicitudin, lectus augue euismod purus, sed congue velit nibh ac enim. Vivamus mattis mattis lectus non tincidunt. Nulla pretium nisl ac massa euismod, a eleifend turpis blandit. Aliquam imperdiet vitae magna in accumsan. Vivamus imperdiet magna purus, sed consequat mi interdum vel. Morbi fringilla, nisi faucibus bibendum tempor, odio nisi scelerisque augue, tincidunt maximus orci sem dignissim ante. Duis eleifend nunc nec augue bibendum tempus. Phasellus pulvinar orci ut mi fringilla, nec faucibus sapien consectetur. Vivamus nec justo nibh. Maecenas non sodales ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse potenti.
        Nam consectetur fringilla ante, et mollis turpis aliquam a. Donec tristique eros vel eros accumsan, a convallis felis lacinia. Nulla vel tristique magna. Aenean leo justo, cursus ac dictum nec, fringilla vel massa. Pellentesque suscipit mauris sem, a vulputate nunc egestas non. Nunc a mattis libero, ac maximus ante. Curabitur euismod ex id ex varius tempor. Donec tristique ipsum augue, eget volutpat nisi suscipit tincidunt. Nam gravida nunc ut enim fringilla, in faucibus diam efficitur. Phasellus risus purus, ultricies non risus sed, suscipit vestibulum turpis. Suspendisse potenti. Curabitur tempus a mi vel euismod. Fusce semper diam id elementum pellentesque. Suspendisse ultricies nec dui at sagittis. Phasellus ultrices libero ante, quis varius metus ultrices sit amet.
        Nulla ac lorem nec odio vestibulum commodo at non justo. Cras ultrices finibus lacus, et ornare nisi feugiat quis. Nulla tempor, ipsum sit amet vulputate congue, turpis sapien imperdiet turpis, in interdum justo sapien sed est. Aenean lectus massa, facilisis quis volutpat non, luctus et justo. Quisque pellentesque neque quis odio luctus rhoncus. Aliquam pulvinar dapibus metus, id fermentum ipsum sagittis a. Suspendisse faucibus, turpis nec consequat vehicula, arcu nulla tempor leo, nec varius metus nibh ac nulla.
        Praesent varius gravida velit, sit amet hendrerit nulla rutrum quis. Curabitur vitae dolor vehicula, lacinia purus a, aliquam orci. Nunc imperdiet sapien eget turpis hendrerit lobortis. Fusce aliquam eros vitae fermentum elementum. Cras a tincidunt magna, id rutrum tortor. Suspendisse potenti. Nullam sed ipsum commodo, laoreet erat id, tempus arcu. Maecenas ultricies, est at congue iaculis, arcu sem consectetur turpis, in tincidunt quam metus at nibh. Sed placerat, enim sed scelerisque suscipit, metus nibh dapibus arcu, et mattis eros ante eu lectus. Nam quis elementum enim. Nulla quis sagittis metus. Cras aliquam eget ante eget feugiat. Maecenas sed porttitor est, eu porttitor sapien. Mauris nec efficitur libero. Mauris auctor arcu vitae accumsan fermentum. Proin id massa lorem.
        Quisque a quam ut massa iaculis lacinia. Fusce dignissim suscipit dapibus. Duis tortor lectus, vehicula ut risus non, ultrices aliquet tortor. Sed in venenatis ex. Aenean volutpat ultrices justo sit amet euismod. Curabitur magna augue, aliquam ut convallis id, tempor sollicitudin enim. Phasellus nec leo ut nisi aliquet interdum sit amet at eros. Sed sit amet mauris mi. Phasellus ac orci imperdiet, commodo sapien a, auctor nunc. Vivamus sed est in dolor pulvinar efficitur. Donec tempus auctor mauris, et lacinia lectus accumsan a. Vivamus neque urna, ullamcorper a lacus sed, pharetra convallis orci.
        Aliquam venenatis auctor mi. In ac dictum dolor. Maecenas nec efficitur ipsum. Nulla vitae massa venenatis urna tempus pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce euismod enim eu ullamcorper euismod. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus in felis nibh. Curabitur sodales eleifend tellus, porta venenatis libero facilisis sed. Proin quis tempor lectus, ut posuere urna.
        Mauris id turpis facilisis, dictum purus quis, tempus ante. Maecenas sollicitudin nulla imperdiet quam tristique, id lacinia turpis malesuada. Integer lobortis varius magna, at lacinia augue suscipit eu. Nulla malesuada pellentesque ipsum, quis placerat ipsum euismod non. Nunc quis tempor quam. Morbi scelerisque sapien nibh, eu scelerisque est rutrum a. Praesent id diam nec felis iaculis tristique sit amet ac odio. Aliquam sodales, lacus a hendrerit laoreet, neque elit mattis leo, non efficitur magna arcu vel lorem. Ut ac nibh dictum, sodales velit quis, placerat libero. Aliquam id elementum enim. Sed gravida erat porttitor metus commodo sodales. Pellentesque scelerisque cursus lectus sit amet convallis.
        In hac habitasse platea dictumst. Nulla ut egestas erat. Maecenas malesuada, nulla vel facilisis lacinia, mi metus auctor odio, ut sodales risus enim in purus. Cras a pharetra arcu. Vestibulum vel dui eget libero dapibus tristique. Quisque suscipit consectetur lectus, eget interdum massa fermentum commodo. Duis eget enim est. Suspendisse luctus ultrices magna at sodales. Aliquam finibus eget orci quis molestie.
        Fusce ullamcorper suscipit lectus, vel pellentesque lorem dignissim sit amet. Suspendisse egestas sem libero, sit amet auctor ex volutpat nec. Cras gravida vel sapien id tincidunt. In tempus laoreet lectus, nec lacinia lorem laoreet ut. Etiam lobortis, tortor ac feugiat ornare, metus justo scelerisque lorem, quis vulputate sem sapien non nunc. Vestibulum vitae est at massa sagittis tristique rhoncus sit amet enim. Integer hendrerit, metus vel blandit convallis, velit arcu tincidunt augue, a finibus erat quam a est.
        Vivamus nunc sapien, malesuada elementum augue eu, faucibus commodo ante. In dapibus vestibulum suscipit. Praesent bibendum risus mauris, lobortis efficitur nibh pretium non. Suspendisse potenti. Aenean id nisi diam. Maecenas sit amet sollicitudin velit. Nullam sed pretium erat, non imperdiet metus. Sed condimentum, ante commodo condimentum tempor, sapien nulla finibus felis, sit amet elementum neque velit vel purus.
        Etiam sit amet justo lobortis nulla dapibus interdum vitae vel massa. Sed aliquam consectetur auctor. Morbi ac pharetra risus. Cras tempor dui vitae justo vestibulum viverra. Vivamus id semper risus. Aenean cursus venenatis odio vel congue. Phasellus congue pulvinar sem, ac lacinia sapien lacinia imperdiet. Integer eu euismod metus, non tincidunt sem. Nulla porttitor consequat bibendum. Nullam ultrices risus lectus, ac tristique turpis tempor eu. Aliquam porta venenatis massa, ut ultrices odio elementum et. Maecenas egestas sapien eget erat bibendum finibus vitae non arcu. Vivamus auctor ipsum eget diam lobortis, eu imperdiet nisi lobortis. Praesent elit est, elementum id est a, maximus accumsan arcu.
        Vivamus sodales at risus vel sodales. Phasellus facilisis lectus sit amet ligula scelerisque volutpat. Nunc in metus sapien. Phasellus sed metus in enim cursus aliquet. Aliquam aliquam, urna eu laoreet porta, dolor velit sollicitudin odio, luctus molestie dui lacus eget orci. Cras tincidunt vulputate tempus. Vestibulum in leo mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam scelerisque bibendum sodales. Pellentesque convallis neque leo, sed bibendum mauris tempus non. Morbi id suscipit justo. Aenean sed lobortis ipsum.
        Cras in pulvinar enim. Aliquam erat volutpat. Aliquam id molestie tellus, vel lobortis ex. Nulla sagittis turpis leo, eu dignissim quam tempor ac. Praesent eleifend lorem maximus tempor pulvinar. Sed tincidunt velit non maximus molestie. Cras ut mattis mauris, ut dictum magna. Pellentesque gravida pharetra nunc porttitor mattis. Curabitur gravida neque varius ex tincidunt, eget commodo tellus ornare. Donec a interdum massa.
        Nulla suscipit erat at leo lobortis varius. Nullam mollis tempor efficitur. Etiam fringilla risus et est vulputate, ut gravida ipsum semper. Aenean ullamcorper tempor rutrum. Ut nec ipsum quis tortor porta faucibus. Vestibulum sollicitudin finibus orci. Sed finibus mi ac tortor bibendum dignissim. Suspendisse potenti. Nullam elementum malesuada diam, eu gravida libero consectetur scelerisque. Proin porta, libero at venenatis molestie, purus mi ultrices lectus, nec placerat dolor enim ut ex. Nam ullamcorper justo at fermentum feugiat. Quisque facilisis accumsan eros, quis hendrerit lacus elementum et.
        Praesent vel pellentesque lorem, eu venenatis massa. Proin commodo consequat leo, a suscipit nibh tincidunt ut. Donec finibus nisi ac lobortis imperdiet. Nulla ultricies quam libero, ac bibendum neque vehicula sed. Nunc vel ipsum metus. In sit amet rutrum erat, vitae iaculis ipsum. Etiam commodo lectus sit amet justo volutpat, id consectetur eros tincidunt. Phasellus a dictum elit. Sed quis ex et quam posuere efficitur. Etiam quis euismod tellus, non iaculis tellus. Suspendisse suscipit tristique mi id molestie. Aenean est metus, tincidunt id tellus non, egestas vestibulum ligula. Duis eget tellus congue, auctor lacus sed, pellentesque velit. Phasellus suscipit, mauris at finibus facilisis, urna tortor gravida quam, non maximus nisi nibh quis urna. Mauris sit amet consequat nulla.
        Phasellus placerat elit leo, consectetur porttitor ipsum porta a. Nullam id enim vitae ex suscipit tempus porttitor eget dui. Maecenas enim lectus, mattis sed orci molestie, consectetur rutrum metus. In maximus orci eu sem vestibulum interdum. Curabitur ultricies orci nec elit condimentum maximus at a tortor. Nulla mi libero, rhoncus sed arcu eget, semper finibus sapien. Vivamus dignissim odio quis lectus vehicula condimentum. Sed erat elit, consequat id cursus ut, bibendum a orci. Mauris auctor, nibh a pellentesque pellentesque, lectus lacus feugiat erat, sodales vestibulum odio dolor auctor elit. In eget lacus libero. Phasellus fringilla risus finibus posuere congue. Suspendisse pellentesque, est et sollicitudin luctus, ipsum enim scelerisque urna, id congue quam velit a tellus. Vestibulum pulvinar leo a sollicitudin aliquam. Praesent erat nulla, commodo at euismod sit amet, mattis sit amet risus. Suspendisse eget orci lectus.
        Pellentesque quis turpis quis urna cursus rhoncus ut sed dui. Proin erat augue, ornare eu purus vel, efficitur mollis metus. Cras pulvinar luctus ligula at posuere. Ut nec pellentesque diam. Proin gravida lobortis orci ut congue. Maecenas tempus augue a arcu pretium, vitae hendrerit nisi pharetra. Aliquam sit amet ultrices massa, nec iaculis magna. Nam commodo urna vitae purus porttitor placerat. Cras finibus quis purus vel venenatis. Vestibulum bibendum aliquet elit, a iaculis neque finibus at. Pellentesque ut aliquet leo. Proin ut mauris ac tellus tristique lacinia.
        Vestibulum eget purus euismod, molestie mi sit amet, vulputate risus. Quisque vitae tortor a nisi volutpat efficitur et ac massa. Cras a neque sed sem luctus dictum ut et mauris. In quis finibus ex, sit amet pharetra risus. Nulla sit amet augue non ante hendrerit sodales ut quis lectus. Donec tincidunt mauris id tincidunt fermentum. Nam vel nisi posuere, ullamcorper risus quis, placerat ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer vitae tellus eu ligula placerat ultrices. Cras finibus gravida tincidunt. Pellentesque blandit, dui nec lacinia scelerisque, tortor orci congue ante, fringilla eleifend metus ante id justo. Vivamus urna urna, consectetur ac diam non, convallis feugiat erat. Phasellus convallis, lacus nec vestibulum tristique, urna quam mattis libero, eget viverra dui justo ut nisl.</p>
    </div>
  </main>
</body>

</html>